name: Check JavaScript

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint_test:
    name: Lint and test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      # - name: Install Firefox
      #   uses: browser-actions/setup-firefox@v1

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm
        # Install the version of npm that is required to build the project.
        run: npm install -g npm@10

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Generate coverage report
        run: npm run coverage

